# .github/release.yml

changelog:
  exclude:
    labels:
      - duplicate
      - wontfix
      - help wanted
      - invalid
      - question
  categories:
    - title: 이슈 해결 🛠️
      labels:
        - resolved
    - title: 버그 수정 🐞
      labels:
        - bug
    - title: 기능 추가 및 개선 🎉
      labels:
        - enhancement
    - title: 릴리즈 (Major) 📢
      labels:
        - release/major
    - title: 릴리즈 (Minor) 📢
      labels:
        - release/minor
    - title: 릴리즈 (Patch) 📢
      labels:
        - release/patch
    - title: 기타
      labels:
        - "*"