name: Bump version tag

on:
  workflow_call:
    outputs:
      new_version:
        value: ${{ jobs.tagging.outputs.new_version }}
      tag:
        value: ${{ jobs.tagging.outputs.tag }}
      part:
        value: ${{ jobs.tagging.outputs.part }}

jobs:
  tagging:
    name: Bump version tag
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-20.04

    outputs:
      new_version: ${{ steps.tag_version.outputs.new_tag }}
      tag: ${{ steps.tag_version.outputs.tag }}
      part: ${{ steps.tag_version.outputs.part }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: keepbang/issue-approval@v1.0.0
        with:
          secret-token: ${{ secrets.GITHUB_TOKEN }}
          # todo: Add all of team members
          approvers: sghwang-mcorpor,keepbang

      - name: Bump version and push tag
        id: tag_version
        uses: keepbang/bump-tag-version@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch # pr 날릴때 major 추가해서 사용