name: Bump version tag

on:
  workflow_call:
    outputs:
      new_version: ${{ jobs.tagging.outputs.new_version }}
      tag: ${{ jobs.tagging.outputs.tag }}
      part: ${{ jobs.tagging.outputs.part }}

jobs:
  tagging:
    name: Bump version tag
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-20.04

    outputs:
      new_version: ${{ steps.tag_version.outputs.new_tag }}
      tag: ${{ steps.tag_version.outputs.tag }}
      part: ${{ steps.tag_version.outputs.part }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          # todo: Add all of team members
          approvers: sghwang-mcorpor,keepbang
          minimum-approvals: 1

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch # pr 날릴때 major 추가해서 사용