name: Create next major and minor version branches

on:
  workflow_call:
    inputs:
      next_major_version:
        required: true
        type: string
      next_minor_version:
        required: true
        type: string
      part:
        required: true
        type: string
    outputs:
      major_created:
        value: ${{ jobs.create_next_major_branch.outputs.created }}
      minor_created:
        value: ${{ jobs.create_next_minor_branch.outputs.created }}
      next_major_version:
        value: ${{ jobs.create_next_major_branch.outputs.next_version }}
      next_minor_version:
        value: ${{ jobs.create_next_minor_branch.outputs.next_version }}

jobs:
  create_next_major_branch:
    name: Create next major branch
    if: ${{ inputs.part != 'patch' }}
    runs-on: ubuntu-20.04
    outputs:
      created: ${{ steps.create_branch.outputs.created }}
      next_version: ${{ inputs.next_major_version }}
    steps:
      - name: Create branch
        id: create_branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'major/${{ inputs.next_major_version }}'
          # sha: '${{ github.event.pull_request.head.sha }}'

      - name: Print result
        run: |
          echo ${{ steps.create_branch.outputs.created }}

  create_next_minor_branch:
    name: Create next minor branch
    if: ${{ inputs.part != 'patch' }}
    runs-on: ubuntu-20.04
    outputs:
      created: ${{ steps.create_branch.outputs.created }}
      next_version: ${{ inputs.next_minor_version }}
    steps:
      - name: Create branch
        id: create_branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'minor/${{ inputs.next_minor_version }}'
          # sha: '${{ github.event.pull_request.head.sha }}'

      - name: Print result
        run: |
          echo ${{ steps.create_branch.outputs.created }}