name: Create next major and minor version branches

on:
  workflow_call:
    inputs:
      part:
        required: true
        type: string
    outputs:
      major_created:
        value: ${{ jobs.create_next_major_branch.outputs.created }}
      minor_created:
        value: ${{ jobs.create_next_minor_branch.outputs.created }}
      next_major_version:
        value: ${{ jobs.create_next_major_branch.outputs.next_version }}
      next_minor_version:
        value: ${{ jobs.create_next_minor_branch.outputs.next_version }}

jobs:
  create-next-version:
    name: Create next version
    uses: ./.github/workflows/create-next-semver.yml

  create_next_major_branch:
    name: Create next major branch
    if: ${{ inputs.part != 'patch' }}
    needs: [ create-next-version ]
    runs-on: ubuntu-20.04
    outputs:
      created: ${{ steps.create_branch.outputs.created }}
      next_version: ${{ needs.create-next-version.outputs.next_major_version }}
    steps:
      - name: Create branch
        id: create_branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'major/${{ needs.create-next-version.outputs.next_major_version }}'
          # sha: '${{ github.event.pull_request.head.sha }}'

      - name: Print result
        run: |
          echo ${{ steps.create_branch.outputs.created }}

  create_next_minor_branch:
    name: Create next minor branch
    if: ${{ inputs.part != 'patch' }}
    needs: [ create-next-version ]
    runs-on: ubuntu-20.04
    outputs:
      created: ${{ steps.create_branch.outputs.created }}
      next_version: ${{ needs.create-next-version.outputs.next_minor_version }}
    steps:
      - name: Create branch
        id: create_branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'minor/${{ needs.create-next-version.outputs.next_minor_version }}'
          # sha: '${{ github.event.pull_request.head.sha }}'

      - name: Print result
        run: |
          echo ${{ steps.create_branch.outputs.created }}