name: Create next major and minor version branches.

on:
  workflow_dispatch:  # click the button on Github repo!

jobs:
  get_next_version_tag:
    name: Get next version tag
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Get Previous tag
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get next version
        id: next_version
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previous_tag.outputs.tag }}
    outputs:
      next_major_version: ${{ steps.next_version.outputs.major }}
      next_minor_version: ${{ steps.next_version.outputs.minor }}

  create_next_minor-branch:
    runs-on: ubuntu-20.04
    needs: [get_next_version_tag]
    name: Create next minor branch
    steps:        
      - name: Create branch
        id: create_branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'minor/${{ needs.get_next_version_tag.outputs.next_minor_version }}'
          # sha: '${{ github.event.pull_request.head.sha }}'

      - run: |
          echo ${{ steps.create_branch.outputs.created }}

  create_next_major-branch:
    runs-on: ubuntu-20.04
    needs: [get_next_version_tag]
    name: Create next major branch
    steps:        
      - name: Create branch
        id: create_branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'minor/${{ needs.get_next_version_tag.outputs.next_major_version }}'
          # sha: '${{ github.event.pull_request.head.sha }}'

      - run: |
          echo ${{ steps.create_branch.outputs.created }}
