name: Create next minor branch.

on:
  workflow_dispatch:  # click the button on Github repo!

jobs:
  create_next_minor-branch:
    runs-on: ubuntu-20.04
    name: Create next minor branch
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Get Previous tag
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get next version
        id: next_version
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previous_tag.outputs.tag }}
    
      - name: Create branch
        id: create_branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'minor/${{ steps.next_version.outputs.minor }}'
          # sha: '${{ github.event.pull_request.head.sha }}'

      - run: |
          echo ${{ steps.create_branch.outputs.created }}
