name: Production build.

on:
  pull_request:
    types:
      - closed
    branches: [ "main" ]

env:
  MODULE_NAME_1: app:grassland
  APPLICATION_NAME_1: mco-playground-grassland
  MODULE_NAME_2: app:zoo
  APPLICATION_NAME_2: mco-playground-zoo
  MODULE_NAME_3: aid:employee
  LIBRARY_NAME: employee-object

jobs:
  application-deploy:
    uses: ./.github/workflows/deploy.yml

  branch-release:
    name: released branch rename
    needs: [application-deploy]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check my source
        run: pwd && ls -al

      - name: Set variables
        id: branch_variables
        run: |
          old_branch="${{ needs.application-deploy.outputs.part }}/${{ needs.application-deploy.outputs.tag }}"
          new_branch="${{ needs.application-deploy.outputs.part }}/${{ needs.application-deploy.outputs.tag }}-released"
          echo "OLD_BRANCH=$old_branch" >> $GITHUB_OUTPUT
          echo "NEW_BRANCH=$new_branch" >> $GITHUB_OUTPUT

      - name: Rename released branch
        id: rename_branch
        run: |
          # Rename branch
          # git push <remote> <remote>/<old_name>:refs/heads/<new_name> :<old_name>
          git push origin origin/${{ steps.branch_variables.outputs.OLD_BRANCH }}:refs/heads/${{ steps.branch_variables.outputs.NEW_BRANCH }} :${{ steps.branch_variables.outputs.OLD_BRANCH }}
        if: ${{ needs.application-deploy.outputs.part != 'patch' }}
