name: Production build.

on:
  pull_request:
    types:
      - closed
    branches: [ "main" ]

env:
  MODULE_NAME_1: app:grassland
  APPLICATION_NAME_1: mco-playground-grassland
  MODULE_NAME_2: app:zoo
  APPLICATION_NAME_2: mco-playground-zoo
  MODULE_NAME_3: aid:employee
  LIBRARY_NAME: employee-object

jobs:
  application-deploy:
    uses: ./.github/workflows/deploy.yml

  rename-released-branch:
    name: Rename released branch
    if: ${{ needs.application-deploy.outputs.part != 'patch' }}
    needs: [application-deploy]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check my source
        run: pwd && ls -al

      - name: Set variables
        id: branch_variables
        run: |
          old_branch="${{ needs.application-deploy.outputs.part }}/${{ needs.application-deploy.outputs.tag }}"
          new_branch="${{ needs.application-deploy.outputs.part }}/${{ needs.application-deploy.outputs.tag }}-released"
          echo "OLD_BRANCH=$old_branch" >> $GITHUB_OUTPUT
          echo "NEW_BRANCH=$new_branch" >> $GITHUB_OUTPUT

      - name: Rename branch
        id: rename_branch
        run: |
          # Rename branch
          # git push <remote> <remote>/<old_name>:refs/heads/<new_name> :<old_name>
          git push origin origin/${{ steps.branch_variables.outputs.OLD_BRANCH }}:refs/heads/${{ steps.branch_variables.outputs.NEW_BRANCH }} :${{ steps.branch_variables.outputs.OLD_BRANCH }}


  create-next-version:
    needs: [rename-released-branch]
    uses: ./.github/workflows/create-next-semver.yml


  # name: Create next major and minor version branches.
  create_next_minor-branch:
    name: Create next minor branch
    if: ${{ needs.application-deploy.outputs.part != 'patch' }}
    needs: [create-next-version]
    runs-on: ubuntu-20.04
    steps:
      - name: Create branch
        id: create_branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'minor/${{ needs.create-next-version.outputs.next_minor_version }}'
          # sha: '${{ github.event.pull_request.head.sha }}'

      - name: Print result
        run: |
          echo ${{ steps.create_branch.outputs.created }}

  create_next_major-branch:
    name: Create next major branch
    if: ${{ needs.application-deploy.outputs.part != 'patch' }}
    needs: [create-next-version]
    runs-on: ubuntu-20.04
    steps:
      - name: Create branch
        id: create_branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'major/${{ needs.create-next-version.outputs.next_major_version }}'
          # sha: '${{ github.event.pull_request.head.sha }}'

      - name: Print result
        run: |
          echo ${{ steps.create_branch.outputs.created }}

