name: Production build.

on:
  pull_request:
    types:
      - closed
    branches: [ "main" ]

env:
  MODULE_NAME_1: app:grassland
  APPLICATION_NAME_1: mco-playground-grassland
  MODULE_NAME_2: app:zoo
  APPLICATION_NAME_2: mco-playground-zoo
  MODULE_NAME_3: aid:employee
  LIBRARY_NAME: employee-object

jobs:
  application-deploy:
    uses: ./.github/workflows/deploy.yml

  rename-released-branch:
    name: Rename released branch
    if: ${{ needs.application-deploy.outputs.part != 'patch' }}
    needs: [ application-deploy ]
    runs-on: ubuntu-20.04
    outputs:
      part: ${{ needs.application-deploy.outputs.part }}
      new_version: ${{ needs.application-deploy.outputs.new_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check my source
        run: pwd && ls -al

      - name: Set variables
        id: branch_variables
        run: |
          old_branch="${{ needs.application-deploy.outputs.part }}/${{ needs.application-deploy.outputs.tag }}"
          new_branch="${{ needs.application-deploy.outputs.part }}/${{ needs.application-deploy.outputs.tag }}-released"
          echo "OLD_BRANCH=$old_branch" >> $GITHUB_OUTPUT
          echo "NEW_BRANCH=$new_branch" >> $GITHUB_OUTPUT

      - name: Rename branch
        id: rename_branch
        run: |
          # Rename branch
          # git push <remote> <remote>/<old_name>:refs/heads/<new_name> :<old_name>
          git push origin origin/${{ steps.branch_variables.outputs.OLD_BRANCH }}:refs/heads/${{ steps.branch_variables.outputs.NEW_BRANCH }} :${{ steps.branch_variables.outputs.OLD_BRANCH }}

  # patch가 아닌 경우 branch 생성 후 싱크.
  create-and-sync-branches:
    if: ${{ needs.application-deploy.outputs.part != 'patch' }}
    needs: [ application-deploy ]
    uses: ./.github/workflows/create-and-sync-branch.yml
    with:
      bumped_part: ${{ needs.application-deploy.outputs.part }}
      next_version: ${{ needs.application-deploy.outputs.new_version }}

  # patch일 경우 branch 생성을 건너 뛰고 싱크.
  create-next-version:
    name: Create next version
    needs: [ application-deploy ]
    uses: ./.github/workflows/create-next-semver.yml

  sync-major-branch:
    if: ${{ needs.application-deploy.outputs.part == 'patch' }}
    needs: [ create-next-version ]
    uses: ./.github/workflows/sync-release-trains.yml
    with:
      target_part: major
      next_version: ${{ needs.create-next-version.outputs.next_major_version }}

  sync-minor-branch:
    if: ${{ needs.application-deploy.outputs.part == 'patch' }}
    needs: [ create-next-version ]
    uses: ./.github/workflows/sync-release-trains.yml
    with:
      target_part: minor
      next_version: ${{ needs.create-next-version.outputs.next_minor_version }}